continous_integration_task:
  container:
    dockerfile: divi/DockerfileForCI
  test_script:
    - pushd divi/src/GMock && autoreconf -fvi && popd
    - pushd divi/ && { make distclean || true ; } && ./autogen.sh && ./configure --without-gui NO_QT=1 && popd
    - pushd divi/ && make && make -j check && pushd qa/rpc-tests && ./test_runner.py --exclude proxy_test.py,rpcbind_test.py