os: linux
dist: bionic
language: cpp

services:
  - docker

before_install:
  - sudo apt-get -y install pass

script:
  # Compile from source
  - echo "$DOCKER_TOKEN" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - cd divi
  - docker build -t divi -f DockerfileWithTests .
  - docker run divi
after_failure:
  - cat ./src/test-suite.log