language: cpp
compiler: gcc
install:
  - sudo apt-get install -qq libssl-dev
  - if [ "$BIGNUM" = "gmp" -o "$BIGNUM" = "auto" -o "$FIELD" = "gmp" ]; then sudo apt-get install -qq libgmp-dev; fi
  - if [ "$FIELD" = "64bit_asm" ]; then sudo apt-get install -qq yasm; fi
env:
  global:
    - FIELD=auto  BIGNUM=auto  SCALAR=auto  ENDOMORPHISM=no  BUILD=check  EXTRAFLAGS=
  matrix:
    - SCALAR=32bit
    - SCALAR=64bit
    - FIELD=gmp
    - FIELD=gmp       ENDOMORPHISM=yes
    - FIELD=64bit_asm
    - FIELD=64bit_asm ENDOMORPHISM=yes
    - FIELD=64bit
    - FIELD=64bit     ENDOMORPHISM=yes
    - FIELD=32bit
    - FIELD=32bit     ENDOMORPHISM=yes
    - BIGNUM=none
    - BIGNUM=none     ENDOMORPHISM=yes
    - BUILD=distcheck
    - EXTRAFLAGS=CFLAGS=-DDETERMINISTIC
before_script: ./autogen.sh
script: ./configure --enable-endomorphism=$ENDOMORPHISM --with-field=$FIELD --with-bignum=$BIGNUM --with-scalar=$SCALAR $EXTRAFLAGS && make -j2 $BUILD
os: linux
