#ifndef LOAD_WALLET_RESULT_H
#define LOAD_WALLET_RESULT_H
enum LoadWalletResult
{
    NEW_WALLET_CREATED,
    EXISTING_WALLET_LOADED,
    ERROR_LOADING_WALLET,
    WARNING_LOADING_WALLET,
};
#endif// LOAD_WALLET_RESULT_H