#ifndef TIME_INTERVAL_CONSTANTS
#define TIME_INTERVAL_CONSTANTS
#define NUMBER_OF_SECONDS_IN_A_DAY 3600 * 24.
#define NUMBER_OF_SECONDS_IN_A_MONTH (NUMBER_OF_SECONDS_IN_A_DAY * 30.)
#endif// TIME_INTERVAL_CONSTANTS