mv ./piv_files.txt ./div_files.txt 
mv ./contrib/init/pivxd.init ./contrib/init/divxd.init
mv ./contrib/init/pivxd.openrc ./contrib/init/divxd.openrc
mv ./contrib/init/pivxd.conf ./contrib/init/divxd.conf 
mv ./contrib/init/pivxd.service ./contrib/init/divxd.service 
mv ./contrib/init/pivxd.openrcconf ./contrib/init/divxd.openrcconf 
mv ./contrib/pivx-qt.pro ./contrib/divx-qt.pro 
mv ./contrib/debian/pivx-qt.desktop ./contrib/debian/divx-qt.desktop 
mv ./contrib/debian/pivxd.install ./contrib/debian/divxd.install 
mv ./contrib/debian/pivx-qt.install ./contrib/debian/divx-qt.install 
mv ./contrib/debian/manpages/pivx.conf.5 ./contrib/debian/manpages/divx.conf.5 
mv ./contrib/debian/manpages/pivxd.1 ./contrib/debian/manpages/divxd.1 
mv ./contrib/debian/manpages/pivx-qt.1 ./contrib/debian/manpages/divx-qt.1 
mv ./contrib/debian/pivxd.manpages ./contrib/debian/divxd.manpages 
mv ./contrib/debian/examples/pivx.conf ./contrib/debian/examples/divx.conf 
mv ./contrib/debian/pivxd.examples ./contrib/debian/divxd.examples 
mv ./contrib/debian/pivxd.bash-completion ./contrib/debian/divxd.bash-completion 
mv ./contrib/debian/pivx-qt.lintian-overrides ./contrib/debian/divx-qt.lintian-overrides 
mv ./contrib/debian/pivxd.lintian-overrides ./contrib/debian/divxd.lintian-overrides 
mv ./contrib/debian/pivx-qt.protocol ./contrib/debian/divx-qt.protocol 
mv ./contrib/pivxd.bash-completion ./contrib/divxd.bash-completion 
mv ./src/pivxd.cpp ./src/divxd.cpp 
mv ./src/pivx-cli.cpp ./src/divx-cli.cpp 
mv ./src/test/test_pivx.cpp ./src/test/test_divx.cpp 
mv ./src/qt/zpivcontroldialog.h ./src/qt/zdivcontroldialog.h 
mv ./src/qt/res/images/pivx_logo_horizontal.png ./src/qt/res/images/divx_logo_horizontal.png 
mv ./src/qt/res/icons/unit_pivx.png ./src/qt/res/icons/unit_divx.png 
mv ./src/qt/res/icons/unit_tmpivx.png ./src/qt/res/icons/unit_tmdivx.png 
mv ./src/qt/res/icons/unit_tpivx.png ./src/qt/res/icons/unit_tdivx.png 
mv ./src/qt/res/icons/unit_upivx.png ./src/qt/res/icons/unit_udivx.png 
mv ./src/qt/res/icons/unit_tupivx.png ./src/qt/res/icons/unit_tudivx.png 
mv ./src/qt/res/icons/unit_mpivx.png ./src/qt/res/icons/unit_mdivx.png 
mv ./src/qt/res/pivx-qt-res.rc ./src/qt/res/divx-qt-res.rc 
mv ./src/qt/pivx_locale.qrc ./src/qt/divx_locale.qrc 
mv ./src/qt/locale/pivx_de.ts ./src/qt/locale/divx_de.ts 
mv ./src/qt/locale/pivx_da.ts ./src/qt/locale/divx_da.ts 
mv ./src/qt/locale/pivx_ko_KR.ts ./src/qt/locale/divx_ko_KR.ts 
mv ./src/qt/locale/pivx_ca.ts ./src/qt/locale/divx_ca.ts 
mv ./src/qt/locale/pivx_zh_CN.ts ./src/qt/locale/divx_zh_CN.ts 
mv ./src/qt/locale/pivx_tr.ts ./src/qt/locale/divx_tr.ts 
mv ./src/qt/locale/pivx_ro_RO.ts ./src/qt/locale/divx_ro_RO.ts 
mv ./src/qt/locale/pivx_sk.ts ./src/qt/locale/divx_sk.ts 
mv ./src/qt/locale/pivx_it.ts ./src/qt/locale/divx_it.ts 
mv ./src/qt/locale/pivx_es.ts ./src/qt/locale/divx_es.ts 
mv ./src/qt/locale/pivx_fr_FR.ts ./src/qt/locale/divx_fr_FR.ts 
mv ./src/qt/locale/pivx_uk.ts ./src/qt/locale/divx_uk.ts 
mv ./src/qt/locale/pivx_cs.ts ./src/qt/locale/divx_cs.ts 
mv ./src/qt/locale/pivx_nl.ts ./src/qt/locale/divx_nl.ts 
mv ./src/qt/locale/pivx_en.ts ./src/qt/locale/divx_en.ts 
mv ./src/qt/locale/pivx_sv.ts ./src/qt/locale/divx_sv.ts 
mv ./src/qt/locale/pivx_zh_TW.ts ./src/qt/locale/divx_zh_TW.ts 
mv ./src/qt/locale/pivx_pt_BR.ts ./src/qt/locale/divx_pt_BR.ts 
mv ./src/qt/locale/pivx_en_US.ts ./src/qt/locale/divx_en_US.ts 
mv ./src/qt/locale/pivx_ru.ts ./src/qt/locale/divx_ru.ts 
mv ./src/qt/locale/pivx_hr.ts ./src/qt/locale/divx_hr.ts 
mv ./src/qt/locale/pivx_fi.ts ./src/qt/locale/divx_fi.ts 
mv ./src/qt/locale/pivx_pl.ts ./src/qt/locale/divx_pl.ts 
mv ./src/qt/locale/pivx_pt.ts ./src/qt/locale/divx_pt.ts 
mv ./src/qt/locale/pivx_bg.ts ./src/qt/locale/divx_bg.ts 
mv ./src/qt/locale/pivx_ja.ts ./src/qt/locale/divx_ja.ts 
mv ./src/qt/forms/zpivcontroldialog.ui ./src/qt/forms/zdivcontroldialog.ui 
mv ./src/qt/pivx.qrc ./src/qt/divx.qrc 
mv ./src/qt/zpivcontroldialog.cpp ./src/qt/zdivcontroldialog.cpp 
mv ./src/qt/pivx.cpp ./src/qt/divx.cpp 
mv ./src/qt/pivxstrings.cpp ./src/qt/divxstrings.cpp 
mv ./src/pivxd-res.rc ./src/divxd-res.rc 
mv ./src/pivx-cli-res.rc ./src/divx-cli-res.rc 
mv ./src/pivx-tx.cpp ./src/divx-tx.cpp 
